Create DAO and Entity
daonbm/cg-shopee-app pull request #14
Opened 2024-01-03 10:24 UTC by nguyenthoian

2024-01-03 10:36 UTC, LamChiHung approved these changes

2024-01-03 10:36 UTC, LamChiHung approved these changes
good job

2024-01-04 02:02 UTC, daonguyendev requested changes
Please review my comments below

2024-01-04 02:02 UTC, daonbm commented on build.gradle
> +// https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
Should remove comments

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/controller/HomeController.java
> +
Should remove blank line

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/OrderDao.java
> +    public List<Order> getAllInfo() {
should rename getAllInfo() to getOrderInfo()

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/OrderDao.java
> +                System.out.println("insert order successfully.");
should using log4j instead of sout

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/OrderDao.java
> +                System.out.println("Failed to insert order.");
should using log4j instead of sout

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/OrderDao.java
> +                System.out.println("delete order successfully.");
should using log4j instead of sout

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/OrderDao.java
> +                System.out.println("Failed to delete order.");
should using log4j instead of sout

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/ProductDao.java
> +    //    kiem tra xem ton tai hay chua
Should remove comment

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/ProductDao.java
> +                product.setIdUser(resultSet.getString("user_id"));
Should rename setIdUser to setUserId

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/UserDao.java
> +
Remove blank line

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/UserDao.java
> +                System.out.println("Added user successfully.");
Should use log4j instead of sout

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/dao/UserDao.java
> +                System.out.println("Failed to insert user.");
Should use log4j instead of sout

2024-01-04 02:02 UTC, daonbm commented on src/main/java/com/codegym/cgshopeeapp/model/entity/Order.java
> +
Remove blank line

2024-01-04 02:02 UTC, daonguyendev commented on src/main/java/com/codegym/cgshopeeapp/model/entity/User.java
> +    private String nameUser;
in class User, we understand properties of User, should rename to email, username, password, address,...

2024-01-04 02:02 UTC, daonguyendev commented on src/main/webapp/resource/js/login-form.js
> +function messageCheckInput() {
Should use verb first at function name -> Should rename to checkInputMessage

2024-01-04 03:23 UTC, NgMinhPhuong approved these changes
good

2024-01-04 03:30 UTC, closed without merging